-- ==========================================================
--- tabla sbr11_narino
-- ==========================================================
-- Tabla Estudiantes
-- Tabla Familia
-- Tabla Colegios
-- Tabla Materias

-- Tabla Pruebas (Resultados) ---> Como regNotas

-- Tabla municipios - (presentacion)
-- Tabla departamentos - (presentacion)

---- "2 FORMAR NORMAL"

insert into estudiantes(ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,ESTU_FECHANACIMIENTO,
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
ESTU_TIENEETNIA,
ESTU_ETNIA,
ESTU_LIMITA_MOTRIZ,
ESTU_DEPTO_RESIDE,
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
ESTU_DEDICACIONLECTURADIARIA,
ESTU_DEDICACIONINTERNET,
ESTU_HORASSEMANATRABAJA,
ESTU_TIPOREMUNERACION,
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION,
ESTU_NSE_ESTABLECIMIENTO,
ESTU_INSE_INDIVIDUAL,
ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
ESTU_GENERACIONE)
(select ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,ESTU_FECHANACIMIENTO,
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
ESTU_TIENEETNIA,
ESTU_ETNIA,
ESTU_LIMITA_MOTRIZ,
ESTU_DEPTO_RESIDE,
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
ESTU_DEDICACIONLECTURADIARIA,
ESTU_DEDICACIONINTERNET,
ESTU_HORASSEMANATRABAJA,
ESTU_TIPOREMUNERACION,
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION,
ESTU_NSE_ESTABLECIMIENTO,
ESTU_INSE_INDIVIDUAL,
ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
ESTU_GENERACIONE
from
sbr11_20182)
--------------------------------------------------
insert into familia(
FAMI_ESTRATOVIVIENDA,
FAMI_PERSONASHOGAR,
FAMI_CUARTOSHOGAR,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE,
FAMI_TRABAJOLABORPADRE,
FAMI_TRABAJOLABORMADRE,
FAMI_TIENEINTERNET,
FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR,
FAMI_TIENELAVADORA,
FAMI_TIENEHORNOMICROOGAS,
FAMI_TIENEAUTOMOVIL,
FAMI_TIENEMOTOCICLETA,
FAMI_TIENECONSOLAVIDEOJUEGOS,
FAMI_NUMLIBROS,
FAMI_COMELECHEDERIVADOS, -------
FAMI_COMECARNEPESCADOHUEVO,-----
FAMI_COMECEREALFRUTOSLEGUMBRE,--
FAMI_SITUACIONECONOMICA)

(select FAMI_ESTRATOVIVIENDA,
FAMI_PERSONASHOGAR,
FAMI_CUARTOSHOGAR,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE,
FAMI_TRABAJOLABORPADRE,
FAMI_TRABAJOLABORMADRE,
FAMI_TIENEINTERNET,
FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR,
FAMI_TIENELAVADORA,
FAMI_TIENEHORNOMICROOGAS,
FAMI_TIENEAUTOMOVIL,
FAMI_TIENEMOTOCICLETA,
FAMI_TIENECONSOLAVIDEOJUEGOS,
FAMI_NUMLIBROS,
FAMI_COMELECHEDERIVADOS,
FAMI_COMECARNEPESCADOHUEVO,
FAMI_COMECEREALFRUTOSLEGUMBRE,
FAMI_SITUACIONECONOMICA
from
sbr11_20182)
--------------------------------------------------
insert into colegios(
COLE_CODIGO_ICFES,
COLE_COD_DANE_ESTABLECIMIENTO,
COLE_NOMBRE_ESTABLECIMIENTO,
COLE_GENERO,
COLE_NATURALEZA,
COLE_CALENDARIO,
COLE_BILINGUE,
COLE_CARACTER,
COLE_COD_DANE_SEDE,
COLE_NOMBRE_SEDE,
COLE_SEDE_PRINCIPAL,
COLE_AREA_UBICACION,
COLE_JORNADA,
COLE_COD_MCPIO_UBICACION,
COLE_MCPIO_UBICACION,
COLE_COD_DEPTO_UBICACION,
COLE_DEPTO_UBICACION,
)

(select COLE_CODIGO_ICFES,
COLE_COD_DANE_ESTABLECIMIENTO,
COLE_NOMBRE_ESTABLECIMIENTO,
COLE_GENERO,
COLE_NATURALEZA,
COLE_CALENDARIO,
COLE_BILINGUE,
COLE_CARACTER,
COLE_COD_DANE_SEDE,
COLE_NOMBRE_SEDE,
COLE_SEDE_PRINCIPAL,
COLE_AREA_UBICACION,
COLE_JORNADA,
COLE_COD_MCPIO_UBICACION,
COLE_MCPIO_UBICACION,
COLE_COD_DEPTO_UBICACION,
COLE_DEPTO_UBICACION
from
sbr11_20182)
--------------------------------------------------

inser into materias(
PUNT_LECTURA_CRITICA,
PERCENTIL_LECTURA_CRITICA,
DESEMP_LECTURA_CRITICA,
PUNT_MATEMATICAS,
PERCENTIL_MATEMATICAS,
DESEMP_MATEMATICAS,
PUNT_C_NATURALES,
PERCENTIL_C_NATURALES,
DESEMP_C_NATURALES,
PUNT_SOCIALES_CIUDADANAS,
PERCENTIL_SOCIALES_CIUDADANAS,
DESEMP_SOCIALES_CIUDADANAS,
PUNT_INGLES,
PERCENTIL_INGLES,
DESEMP_INGLES,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
)
(select PUNT_LECTURA_CRITICA,
PERCENTIL_LECTURA_CRITICA,
DESEMP_LECTURA_CRITICA,
PUNT_MATEMATICAS,
PERCENTIL_MATEMATICAS,
DESEMP_MATEMATICAS,
PUNT_C_NATURALES,
PERCENTIL_C_NATURALES,
DESEMP_C_NATURALES,
PUNT_SOCIALES_CIUDADANAS,
PERCENTIL_SOCIALES_CIUDADANAS,
DESEMP_SOCIALES_CIUDADANAS,
PUNT_INGLES,
PERCENTIL_INGLES,
DESEMP_INGLES,
PUNT_GLOBAL,
PERCENTIL_GLOBAL
from
sbr11_20182)


-------SCRIPT DESDE AQUI----------
create table sbr11_20182
(
ESTU_TIPODOCUMENTO text,
ESTU_NACIONALIDAD text,
ESTU_GENERO text,
ESTU_FECHANACIMIENTO text,
PERIODO text,
ESTU_CONSECUTIVO text,
ESTU_ESTUDIANTE text,
ESTU_PAIS_RESIDE text,
ESTU_TIENEETNIA text,
ESTU_ETNIA text,
ESTU_LIMITA_MOTRIZ text,
ESTU_DEPTO_RESIDE text,
ESTU_COD_RESIDE_DEPTO text,
ESTU_MCPIO_RESIDE text,
ESTU_COD_RESIDE_MCPIO text,
FAMI_ESTRATOVIVIENDA text,
FAMI_PERSONASHOGAR text,
FAMI_CUARTOSHOGAR text,
FAMI_EDUCACIONPADRE text,
FAMI_EDUCACIONMADRE text,
FAMI_TRABAJOLABORPADRE text,
FAMI_TRABAJOLABORMADRE text,
FAMI_TIENEINTERNET text,
FAMI_TIENESERVICIOTV text,
FAMI_TIENECOMPUTADOR text,
FAMI_TIENELAVADORA text,
FAMI_TIENEHORNOMICROOGAS text,
FAMI_TIENEAUTOMOVIL text,
FAMI_TIENEMOTOCICLETA text,
FAMI_TIENECONSOLAVIDEOJUEGOS text,
FAMI_NUMLIBROS text,
FAMI_COMELECHEDERIVADOS text,
FAMI_COMECARNEPESCADOHUEVO text,
FAMI_COMECEREALFRUTOSLEGUMBRE text,
FAMI_SITUACIONECONOMICA text,
ESTU_DEDICACIONLECTURADIARIA text,
ESTU_DEDICACIONINTERNET text,
ESTU_HORASSEMANATRABAJA text,
ESTU_TIPOREMUNERACION text,
COLE_CODIGO_ICFES text,
COLE_COD_DANE_ESTABLECIMIENTO text,
COLE_NOMBRE_ESTABLECIMIENTO text,
COLE_GENERO text,
COLE_NATURALEZA text,
COLE_CALENDARIO text,
COLE_BILINGUE text,
COLE_CARACTER text,
COLE_COD_DANE_SEDE text,
COLE_NOMBRE_SEDE text,
COLE_SEDE_PRINCIPAL text,
COLE_AREA_UBICACION text,
COLE_JORNADA text,
COLE_COD_MCPIO_UBICACION text,
COLE_MCPIO_UBICACION text,
COLE_COD_DEPTO_UBICACION text,
COLE_DEPTO_UBICACION text,
ESTU_PRIVADO_LIBERTAD text,
ESTU_COD_MCPIO_PRESENTACION text,
ESTU_MCPIO_PRESENTACION text,
ESTU_DEPTO_PRESENTACION text,
ESTU_COD_DEPTO_PRESENTACION text,
PUNT_LECTURA_CRITICA text,
PERCENTIL_LECTURA_CRITICA text,
DESEMP_LECTURA_CRITICA text,
PUNT_MATEMATICAS text,
PERCENTIL_MATEMATICAS text,
DESEMP_MATEMATICAS text,
PUNT_C_NATURALES text,
PERCENTIL_C_NATURALES text,
DESEMP_C_NATURALES text,
PUNT_SOCIALES_CIUDADANAS text,
PERCENTIL_SOCIALES_CIUDADANAS text,
DESEMP_SOCIALES_CIUDADANAS text,
PUNT_INGLES text,
PERCENTIL_INGLES text,
DESEMP_INGLES text,
PUNT_GLOBAL text,
PERCENTIL_GLOBAL text,
ESTU_NSE_ESTABLECIMIENTO text,
ESTU_INSE_INDIVIDUAL text,
ESTU_NSE_INDIVIDUAL text,
ESTU_ESTADOINVESTIGACION text,
ESTU_GENERACIONE text
);
-------------------------------------------------------------------------------------
-- poblar tabla a partir de archivo plano
-------------------------------------------------------------------------------------
copy sbr11_20182 from 'D:\admon bases de datos\proyecto normalizacion\archivo icfes\sbr11_20182.csv'
with (delimiter '|',format 'csv',encoding 'UTF-8',header);
--COPY 549934
--Query returned successfully in 11 secs 234 msec.
select * from sbr11_20182 limit 100;
----------------------------------------------------------------------------------
-- CREAR LA TABLA SBR11_NARINO_182
-----------------------------------------------------------------------------------
create table sbr11_narino_182 as
select * from sbr11_20182 where estu_depto_reside like 'NARI_O'
-- SELECT 17205
-- Query returned successfully in 513 msec.
-----------------------------------------------------------------------------------












